# Generated by Django 4.2.5 on 2023-11-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('code', models.CharField(default='', max_length=255, verbose_name='code')),
                ('description', models.CharField(default='', max_length=255, verbose_name='description')),
                ('regional_branch', models.CharField(default='', max_length=255, verbose_name='regional branch')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('abacus_id', models.BigIntegerField(default=0, verbose_name='abacus id')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('abacus_id', models.BigIntegerField(default=0, verbose_name='abacus id')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'regions',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name')),
                ('abacus_id', models.BigIntegerField(default=0, verbose_name='abacus id')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='division.region')),
            ],
            options={
                'verbose_name': 'town',
                'verbose_name_plural': 'towns',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name')),
                ('abacus_id', models.BigIntegerField(default=0, verbose_name='abacus id')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='division.town')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
            },
        ),
    ]
