# Generated by Django 4.1.2 on 2024-03-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0005_alter_currencyexchange_currency_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchange',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='currencyexchange',
            name='rate',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='rate'),
        ),
    ]
