# Generated by Django 4.1.2 on 2024-03-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0006_alter_currencyexchange_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='abacus_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='abacus id'),
        ),
    ]
