# Generated by Django 4.1.2 on 2024-03-27 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0007_currency_abacus_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currencyexchange',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchange',
            unique_together={('date', 'currency_from', 'currency_to')},
        ),
    ]
