# Generated by Django 4.1.2 on 2024-07-15 12:35

from django.db import migrations
from division.models.currency import Currency

class Migration(migrations.Migration):

    def add_currencies(apps, schema_editor):
        print('not need this code')
        # Currency.objects.create(uid="TJS", name="Somoni", code="TJS", description="Сомони", abacus_id=18)
        # Currency.objects.create(uid="USD", name="United State Dollar", code="USD", description="Доллари ИМА", abacus_id=1)
        # Currency.objects.create(uid="RUB", name="Russian Ruble", code="RUB", description="Российский рубль", abacus_id=810)
        # Currency.objects.create(uid="EUR", name="European Euro", code="EUR", description="Европейское Евро", abacus_id=978)

    dependencies = [
        ('division', '0009_alter_currency_uid'),
    ]

    operations = [
        migrations.RunPython(add_currencies),
    ]