# Generated by Django 4.1.2 on 2024-01-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_helpdesk_created_by_helpdesk_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpdesk',
            options={'permissions': [('can-view-all_helpdesks', 'Can view all helpdesks')], 'verbose_name': 'helpdesk', 'verbose_name_plural': 'helpdesk'},
        ),
    ]