# Generated by Django 4.1.2 on 2024-02-12 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
        ('helpdesk', '0003_alter_helpdesk_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdesk',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='division.branch'),
        ),
        migrations.DeleteModel(
            name='Helpdesk_Branch',
        ),
    ]
