# Generated by Django 4.1.2 on 2024-02-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    def add_priorities(apps, schema_editor):
        Helpdesk_Priority = apps.get_model('helpdesk', 'Helpdesk_Priority')
        Helpdesk_Priority.objects.create(name='Низкий',uid = "LOW")
        Helpdesk_Priority.objects.create(name='Средний',uid = "MEDIUM")
        Helpdesk_Priority.objects.create(name='Высокий',uid = "HIGH")
        Helpdesk_Priority.objects.create(name='Срочный',uid = "Urgent")

    def add_statuses(apps, schema_editor):
        Helpdesk_Status = apps.get_model('helpdesk', 'Helpdesk_Status')
        Helpdesk_Status.objects.create(name='Открыто',uid = "OPEN")
        Helpdesk_Status.objects.create(name='Закрыто',uid = "CLOSE")
        Helpdesk_Status.objects.create(name='Приостановлено',uid = "POSTPONED")
        Helpdesk_Status.objects.create(name='Уточнение',uid = "CLARIFY")
        Helpdesk_Status.objects.create(name='В работе', uid = "PROGRESS")
        Helpdesk_Status.objects.create(name='В тестировании',uid = "TESTING")
    dependencies = [
        ('helpdesk', '0004_alter_helpdesk_branch_delete_helpdesk_branch'),
    ]

    operations = [
         migrations.RunPython(add_priorities),
          migrations.RunPython(add_statuses),
    ]
