# Generated by Django 4.2.5 on 2023-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='comment'),
        ),
    ]
