# Generated by Django 4.1.2 on 2023-12-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AddField(
            model_name='user',
            name='smart_loan_role',
            field=models.CharField(choices=[('non-smart-loan', 'Пользователь не связан с Smart Loan'), ('customer-service-specialist', 'Специалиста по обслуживанию клиентов'), ('operation-officer', 'Операционный офицер'), ('manager', 'ДФ/РЦМО'), ('cashier', 'Кассир'), ('underwriter', 'Руководителя отдела Андеррайтинга'), ('credit-officer', 'Кредитный офицер'), ('call-officer', 'Агент колл-центра')], default='non-smart-loan', max_length=50, verbose_name='smart loan role'),
        ),
    ]
