# Generated by Django 4.1.2 on 2023-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_user_role_user_smart_loan_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='smart_loan_role',
            field=models.CharField(choices=[('non-smart-loan', 'Пользователь не связан с Smart Loan'), ('customer-service-specialist', 'Специалиста по обслуживанию клиентов'), ('call-officer', 'Агент колл-центра'), ('operation-officer', 'Операционный офицер'), ('manager', 'ДФ/РЦМО'), ('cashier', 'Кассир'), ('underwriter', 'Руководителя отдела Андеррайтинга'), ('underwriter-manager', 'Андеррайтер')], default='non-smart-loan', max_length=50, verbose_name='smart loan role'),
        ),
    ]
