# Generated by Django 4.1.2 on 2023-12-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
        ('users', '0006_alter_user_smart_loan_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='purchases_reports', to='division.branch', verbose_name='branches'),
        ),
    ]
