# Generated by Django 4.1.2 on 2023-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_branches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='smart_loan_role',
            new_name='swift_loan_role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_swift_loan_user',
            field=models.BooleanField(default=True, verbose_name='Пользователь Swift loan'),
        ),
    ]
