# Generated by Django 4.1.2 on 2023-12-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_smart_loan_role_user_swift_loan_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_swift_loan_user',
            field=models.BooleanField(default=False, verbose_name='Пользователь Swift loan'),
        ),
    ]
