# Generated by Django 4.1.2 on 2023-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_is_swift_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='swift_loan_role',
            field=models.CharField(choices=[('non-smart-loan', 'Пользователь не связан с Smart Loan'), ('customer-service-specialist', 'Специалиста по обслуживанию клиентов'), ('call-officer', 'Агент колл-центра'), ('operation-officer', 'Операционный офицер'), ('manager', 'ДФ/РЦМО'), ('cashier', 'Кассир'), ('underwriter', 'Андеррайтер'), ('underwriter-manager', 'Руководителя отдела Андеррайтинга')], default='non-smart-loan', max_length=50, verbose_name='smart loan role'),
        ),
    ]
