# Generated by Django 4.1.2 on 2023-12-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_swift_loan_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='swift_loan_role',
            field=models.CharField(choices=[('non-swift-loan', 'Пользователь не связан с Swift Loan'), ('customer-service-specialist', 'Специалиста по обслуживанию клиентов'), ('call-officer', 'Агент колл-центра'), ('operation-officer', 'Операционный офицер'), ('manager', 'ДФ/РЦМО'), ('cashier', 'Кассир'), ('underwriter', 'Андеррайтер'), ('underwriter-manager', 'Руководитель отдела Андеррайтинга')], default='non-swift-loan', max_length=50, verbose_name='smart loan role'),
        ),
    ]
