# Generated by Django 4.1.2 on 2024-02-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_user_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view-helpdesk-menu-item_user', 'Can view helpdesk menu item'), ('view-blacklist-menu-item_user', 'Can view blacklist menu item'), ('view-report-menu-item_user', 'Can view report menu item'), ('view-terminal-menu-item_user', 'Can view terminal menu item'), ('view-cibt-menu-item_user', 'Can view cibt menu item'))},
        ),
    ]
