# Generated by Django 4.1.2 on 2024-04-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view-helpdesk-menu-item_user', 'Can view helpdesk menu item'), ('view-blacklist-menu-item_user', 'Can view blacklist menu item'), ('view-report-menu-item_user', 'Can view report menu item'), ('view-terminal-menu-item_user', 'Can view terminal menu item'), ('view-cibt-menu-item_user', 'Can view cibt menu item'), ('view-settings-menu-item_user', 'Can view settings menu item'), ('view-exchange-rate-tab-item_user', 'Can view exchange rate tab item'), ('view-documnet-menu-item_user', 'Can view document menu item'))},
        ),
    ]
