# Generated by Django 4.1.2 on 2024-08-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view-helpdesk-menu-item_user', 'Can view helpdesk menu item'), ('view-blacklist-menu-item_user', 'Can view blacklist menu item'), ('view-report-menu-item_user', 'Can view report menu item'), ('view-terminal-menu-item_user', 'Can view terminal menu item'), ('view-crif-menu-item_user', 'Can view crif menu item'), ('view-settings-menu-item_user', 'Can view settings menu item'), ('view-exchange-rate-tab-item_user', 'Can view exchange rate tab item'), ('view-document-menu-item_user', 'Can view document menu item'), ('view-loan-application-menu-item_user', 'Can view loan application menu item'), ('view-customer-menu-item_user', 'Can view customer menu item'), ('view-call-menu-item_user', 'Can view call menu item'), ('view-abacus-document-tab-item_user', 'Can view abacus document tab item'))},
        ),
    ]
