# Generated by Django 4.1.2 on 2024-08-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='get_full_name',
        ),
    ]
