# Generated by Django 4.2.5 on 2023-11-30 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('code', models.CharField(default='', max_length=255, verbose_name='code')),
            ],
            options={
                'verbose_name': 'Credit purpose',
                'verbose_name_plural': 'Credit purposes',
            },
        ),
        migrations.CreateModel(
            name='EconomicActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Economic activity',
                'verbose_name_plural': 'Economic activities',
            },
        ),
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'rejection reason',
                'verbose_name_plural': 'rejection reasons',
            },
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('uid', models.CharField(blank=True, help_text='Unique identifier for reference to record from code. Do not change if set!', max_length=30, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'request status',
                'verbose_name_plural': 'request statuses',
            },
        ),
        migrations.CreateModel(
            name='RequestCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('client_ID', models.BigIntegerField(blank=True, null=True, verbose_name='Client ID')),
                ('INN', models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='INN')),
                ('Passport_ID', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Passport')),
                ('registration_address_street', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='registartion_address_street')),
                ('address_street', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='address_street')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='division.district')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='division.branch')),
                ('registration_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_address', to='division.district')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_credit.requeststatus')),
            ],
            options={
                'verbose_name': 'request credit',
                'verbose_name_plural': 'request credits',
            },
        ),
        migrations.CreateModel(
            name='EconomicActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('active', models.BooleanField(default=True)),
                ('economic_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Economic_activity', to='request_credit.economicactivity')),
            ],
            options={
                'verbose_name': 'Economic activity type',
                'verbose_name_plural': 'Economic activities types',
            },
        ),
        migrations.CreateModel(
            name='CibtHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('request_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_credit.requestcredit', verbose_name='Кредит')),
            ],
            options={
                'verbose_name': 'CIBT history',
                'verbose_name_plural': 'CIBT histories',
            },
        ),
    ]
