# Generated by Django 4.1.2 on 2023-12-02 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_credit', '0003_requestcredit_created_by_requestcredit_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cibthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='cibthistory',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='cibthistory',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='address street'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='registration_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_address', to='division.district', verbose_name='registration address'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='registration_address_street',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='registration address street'),
        ),
    ]
