# Generated by Django 4.1.2 on 2023-12-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0005_rename_passport_id_requestcredit_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcredit',
            name='date',
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
    ]
