# Generated by Django 4.1.2 on 2023-12-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0007_requestcredit_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcredit',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Муж'), ('female', 'Жен')], max_length=50, null=True, verbose_name='gender'),
        ),
    ]
