# Generated by Django 4.1.2 on 2023-12-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0008_alter_requestcredit_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcredit',
            old_name='birthdate',
            new_name='birthday',
        ),
    ]
