# Generated by Django 4.1.2 on 2023-12-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0009_rename_birthdate_requestcredit_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='family_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='family number'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='family_number_has_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='family number has income'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='family_status',
            field=models.CharField(blank=True, choices=[('married', 'Оиладор'), ('single', 'Мучаррад'), ('separated', 'Чудошуда'), ('widow', 'Бевазан/Мард')], max_length=50, null=True, verbose_name='family_status'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='passport_details',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Passport details'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='phone1',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='phone 1'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='phone 2'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='spouse',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='spouse'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='spouse_phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='spouse phone'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
    ]
