# Generated by Django 4.1.2 on 2023-12-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0010_requestcredit_family_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='acted',
            field=models.CharField(blank=True, choices=[('yes', 'Ха'), ('no', 'Не')], max_length=50, null=True, verbose_name='acted'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='current_debt',
            field=models.CharField(blank=True, choices=[('yes', 'Ха'), ('no', 'Не')], max_length=50, null=True, verbose_name='current_debt'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='current_debt_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='current debt name'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='full_time_employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of full-time employees?'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='information_source',
            field=models.CharField(blank=True, choices=[('tv', 'Реклама дар телевизион'), ('radio', 'Реклама дар радио'), ('newspaper', 'Реклама дар рӯзнома'), ('internet', 'Реклама дар интернет'), ('banner', 'Баннер/шитҳо'), ('oxus', 'Корманди Оксус'), ('third_person', 'Шахси сеюм'), ('other', 'Дигар')], max_length=50, null=True, verbose_name='source of information'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='new_job',
            field=models.IntegerField(blank=True, null=True, verbose_name='creation of new jobs'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='family_status',
            field=models.CharField(blank=True, choices=[('married', 'Оиладор'), ('single', 'Мучаррад'), ('separated', 'Чудошуда'), ('widow', 'Бевазан/Мард')], max_length=50, null=True, verbose_name='family status'),
        ),
    ]
