# Generated by Django 4.1.2 on 2023-12-08 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0012_alter_requestcredit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='economic_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_credit.economicactivity', verbose_name='economic activity'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='economic_activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_credit.economicactivitytype', verbose_name='economic activity type'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='work_experience'),
        ),
    ]
