# Generated by Django 4.1.2 on 2023-12-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
        ('request_credit', '0013_requestcredit_economic_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='credit_purpose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request_credit.creditpurpose', verbose_name='credit purpose'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='currency',
            field=models.CharField(blank=True, choices=[('TJS', 'Сомони'), ('USD', 'Доллари ИМА')], default='TJS', max_length=50, null=True, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='investment_sector',
            field=models.CharField(blank=True, choices=[('trad', 'Савдо'), ('service', 'Хизматрасонӣ'), ('production', 'Истеҳсолот'), ('horticulture', 'Растанипарварӣ'), ('livestock', 'Чорвопарварӣ'), ('cons', 'Истеъмолӣ')], max_length=50, null=True, verbose_name='investment sector'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='request_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='request amount'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='request_grace_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='request grace period'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='request_installment',
            field=models.IntegerField(blank=True, null=True, verbose_name='request amount'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='division.district', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='division.branch'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='economic_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request_credit.economicactivity', verbose_name='economic activity'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='economic_activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request_credit.economicactivitytype', verbose_name='economic activity type'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='registration_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registration_address', to='division.district', verbose_name='registration address'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request_credit.requeststatus'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='work_experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='work experience'),
        ),
    ]
