# Generated by Django 4.1.2 on 2023-12-11 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_credit', '0015_requestcredit_activity_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='status_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='status_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='status change date'),
        ),
    ]
