# Generated by Django 4.1.2 on 2023-12-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('request_credit', '0016_requestcredit_status_change_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='approve_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='approve amount'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='approve_condition',
            field=models.CharField(blank=True, choices=[('after-current', 'Қарз пас аз пардохти қарзи чори дода мешавад'), ('account', 'Хисоббаробаркунӣ'), ('guarantor', 'Қарз бо пешниҳоди зомин дода мешавад')], max_length=50, null=True, verbose_name='approve condition'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='approve_currency',
            field=models.CharField(blank=True, choices=[('TJS', 'Сомони'), ('USD', 'Доллари ИМА')], default='TJS', max_length=50, null=True, verbose_name='approve currency'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='approve_grace_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='approve grace period'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='approve_installment',
            field=models.IntegerField(blank=True, null=True, verbose_name='approve installment'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='approve_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='approve interest'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='approve_issue_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='approve issue fee'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='credit_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='credits.creditproduct', verbose_name='credit product'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='postponed_info',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='rating internal'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='rating_external',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='rating internal'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='rating_internal',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='rating internal'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request_credit.rejectionreason', verbose_name='rejection reason'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='request_installment',
            field=models.IntegerField(blank=True, null=True, verbose_name='request installment'),
        ),
    ]
