# Generated by Django 4.1.2 on 2024-01-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0018_alter_requestcredit_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='application_receipt_channel',
            field=models.CharField(blank=True, choices=[('call-to-call-center', 'Звонок в Колл-центр'), ('online', 'Онлайн заявка'), ('call-from-call-center', 'Звонок от Колл-центра')], max_length=50, null=True, verbose_name='application receipt channel'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='client_decision',
            field=models.CharField(blank=True, choices=[('agree', 'Согласен'), ('refused', 'Отказался'), ('will-think', 'Подумает'), ('missed-call', 'Недозвон'), ('no-information', 'Нет информации')], max_length=50, null=True, verbose_name='client decision'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='client_refused',
            field=models.CharField(blank=True, choices=[('not-need-loan', 'Не нуждается в кредите'), ('commission-fee', 'Наличие комиссионного сбора'), ('high-interest-rates', 'Высокие процентные ставки'), ('client-wants-larger-loan-amount', 'Клиент хочет большую сумму кредита'), ('received-loan', 'Получил кредит'), ('not-eligible-loan-terms', 'Не подхододит по условиям кредитования'), ('not-satisfied-service', 'Не доволен обслуживанием')], max_length=50, null=True, verbose_name='client refused'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='customer_response',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='customer response/comments'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='employee_comments',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='employee comments'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='missed_call',
            field=models.CharField(blank=True, choices=[('not-available', 'Не доступен'), ('not-respond', 'Не отвечает'), ('away-busy', 'Нет на месте(занят)'), ('someone-else-number', 'Чужой номер'), ('outside-Republic', 'За пределами РТ')], max_length=50, null=True, verbose_name='client refused'),
        ),
    ]
