# Generated by Django 4.1.2 on 2024-01-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0019_requestcredit_application_receipt_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='passport_date'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='total_household_assets_info',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='total household assets isnfo'),
        ),
    ]
