# Generated by Django 4.1.2 on 2024-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0020_requestcredit_passport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcredit',
            name='total_household_assets_info',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='total household assets info'),
        ),
    ]
