# Generated by Django 4.1.2 on 2024-02-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0021_alter_requestcredit_total_household_assets_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='cibthistory',
            name='credit_id',
            field=models.CharField(default='', max_length=255, verbose_name='credit_id'),
        ),
    ]
