# Generated by Django 4.1.2 on 2024-02-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0023_cibthistory_client_id_alter_cibthistory_credit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='education',
            field=models.CharField(blank=True, choices=[('master_candidate_doctor', 'Магистр/Номзад/Доктор'), ('university_institute', 'Университет/Институт'), ('college_technical_school', 'Колледж/Техникум'), ('high_school', 'Средняя школа')], max_length=50, null=True, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='education_info',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='education_info'),
        ),
    ]
