# Generated by Django 4.1.2 on 2024-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0024_requestcredit_education_requestcredit_education_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcredit',
            name='education',
            field=models.CharField(blank=True, choices=[('trad', 'Савдо')], max_length=50, null=True, verbose_name='education'),
        ),
    ]
