# Generated by Django 4.1.2 on 2024-02-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0025_alter_requestcredit_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcredit',
            name='education',
            field=models.CharField(blank=True, choices=[('university_institute', 'Донишгоҳ/Донишкада'), ('college_technical_school', 'Коллеҷ/Техникум'), ('high_school', 'Мактаби миёна')], max_length=50, null=True, verbose_name='education'),
        ),
    ]
