# Generated by Django 4.1.2 on 2024-03-04 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0002_currency'),
        ('request_credit', '0027_cibthistory_has_not_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='approve_currency_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approve_currency_new', to='division.currency', verbose_name='approve currency new'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='currency_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_new', to='division.currency', verbose_name='currency new'),
        ),
        migrations.AlterField(
            model_name='cibthistory',
            name='has_not_history',
            field=models.BooleanField(default=False, verbose_name='has not history'),
        ),
    ]
