# Generated by Django 4.1.2 on 2024-04-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0029_remove_requestcredit_approve_currency_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CibtHistory',
        ),
    ]
