# Generated by Django 4.1.2 on 2024-05-06 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_credit', '0030_delete_cibthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('application_receipt_channel', models.CharField(blank=True, choices=[('call-to-call-center', 'Звонок в Колл-центр'), ('online', 'Онлайн заявка'), ('call-from-call-center', 'Звонок от Колл-центра')], max_length=50, null=True, verbose_name='application receipt channel')),
                ('client_decision', models.CharField(blank=True, choices=[('agree', 'Согласен'), ('refused', 'Отказался'), ('will-think', 'Подумает'), ('missed-call', 'Недозвон'), ('no-information', 'Нет информации')], max_length=50, null=True, verbose_name='client decision')),
                ('customer_response', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='customer response/comments')),
                ('employee_comments', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='employee comments')),
                ('client_refused', models.CharField(blank=True, choices=[('not-need-loan', 'Не нуждается в кредите'), ('commission-fee', 'Наличие комиссионного сбора'), ('high-interest-rates', 'Высокие процентные ставки'), ('client-wants-larger-loan-amount', 'Клиент хочет большую сумму кредита'), ('received-loan', 'Получил кредит'), ('not-eligible-loan-terms', 'Не подхододит по условиям кредитования'), ('not-satisfied-service', 'Не доволен обслуживанием')], max_length=50, null=True, verbose_name='client refused')),
                ('missed_call', models.CharField(blank=True, choices=[('not-available', 'Не доступен'), ('not-respond', 'Не отвечает'), ('away-busy', 'Нет на месте(занят)'), ('someone-else-number', 'Чужой номер'), ('outside-Republic', 'За пределами РТ')], max_length=50, null=True, verbose_name='missed call')),
                ('abacus_id', models.BigIntegerField(blank=True, null=True, verbose_name='abacus id')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request_credit.requeststatus')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'Client decision',
                'verbose_name_plural': 'Client decisions',
            },
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='decision_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='request_credit.clientdecision', verbose_name='client decision'),
        ),
    ]
