# Generated by Django 4.1.2 on 2024-05-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0031_clientdecision_requestcredit_decision_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcredit',
            name='application_receipt_channel',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='client_decision',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='client_refused',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='customer_response',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='employee_comments',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='missed_call',
        ),
    ]
