# Generated by Django 4.1.2 on 2024-05-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('request_credit', '0032_remove_requestcredit_application_receipt_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
    ]
