# Generated by Django 4.1.2 on 2024-05-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0033_requestcredit_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdecision',
            name='status',
        ),
    ]
