# Generated by Django 4.1.2 on 2024-05-21 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_credit', '0034_remove_clientdecision_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='underwriter_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='underwriter_request_credit', to='request_credit.requeststatus'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='underwriter_status_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='underwriter_request_credit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='underwriter_status_change_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='underwriter status change date'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_credit', to='request_credit.requeststatus'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='status_change_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_credit', to=settings.AUTH_USER_MODEL),
        ),
    ]
