# Generated by Django 4.1.2 on 2024-06-05 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0035_requestcredit_underwriter_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='client_rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_client_rejection', to='request_credit.rejectionreason', verbose_name='client rejection reason'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='result',
            field=models.CharField(blank=True, choices=[('disbursed', 'Выдано'), ('cancelled', 'Отказано')], max_length=50, null=True, verbose_name='result'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='rejection_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_rejection', to='request_credit.rejectionreason', verbose_name='rejection reason'),
        ),
    ]
