# Generated by Django 4.1.2 on 2024-06-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0036_requestcredit_client_rejection_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcredit',
            name='rating_external',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='rating_internal',
        ),
    ]
