# Generated by Django 4.1.2 on 2024-06-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0037_remove_requestcredit_rating_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcredit',
            name='rating_external',
            field=models.CharField(blank=True, choices=[('yes', 'Ха'), ('no', 'Не')], max_length=50, null=True, verbose_name='rating external'),
        ),
        migrations.AddField(
            model_name='requestcredit',
            name='rating_internal',
            field=models.CharField(blank=True, choices=[('yes', 'Ха'), ('no', 'Не')], max_length=50, null=True, verbose_name='rating internal'),
        ),
    ]
