# Generated by Django 4.1.2 on 2024-07-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('request_credit', '0038_requestcredit_rating_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdecision',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
    ]
