# Generated by Django 4.1.2 on 2024-07-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0039_clientdecision_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdecision',
            name='abacus_id',
        ),
        migrations.AddField(
            model_name='clientdecision',
            name='active_in_abacus',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='uid',
            field=models.CharField(blank=True, help_text='Unique identifier for reference to record from code. Do not change if set!', max_length=100, null=True, unique=True),
        ),
    ]
