# Generated by Django 4.1.2 on 2024-07-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0040_remove_clientdecision_abacus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcredit',
            name='INN',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='client_ID',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='family_status',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='passport_date',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='passport_details',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='phone1',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='phone2',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='registration_address',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='registration_address_street',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='spouse',
        ),
        migrations.RemoveField(
            model_name='requestcredit',
            name='spouse_phone',
        ),
    ]
