# Generated by Django 4.1.2 on 2024-07-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_branch'),
        ('request_credit', '0041_remove_requestcredit_inn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcredit',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
            preserve_default=False,
        ),
    ]
