# Generated by Django 4.1.2 on 2024-07-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0043_alter_requestcredit_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcredit',
            name='postponed_info',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='postponed info'),
        ),
    ]
