# Generated by Django 4.1.2 on 2024-07-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0010_auto_20240715_1235'),
        ('request_credit', '0044_alter_requestcredit_postponed_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcredit',
            name='approve_currency_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approve_currency_new', to='division.currency', verbose_name='approve currency'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='currency_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currency_new', to='division.currency', verbose_name='currency'),
        ),
    ]
