# Generated by Django 4.1.2 on 2024-07-31 13:32

from django.db import migrations
from request_credit.models.client_decision import ClientDecision

def delete_empty_field_records(apps, schema_editor):
    client_decisions = ClientDecision.objects.filter(customer__isnull=True)
    for client_decision in client_decisions:
        client_decision.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('request_credit', '0045_alter_requestcredit_approve_currency_new_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_empty_field_records),
    ]

