# Generated by Django 4.1.2 on 2024-07-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_branch'),
        ('request_credit', '0046_auto_20240731_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdecision',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
        ),
    ]
