# Generated by Django 4.1.2 on 2024-08-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0010_auto_20240715_1235'),
        ('request_credit', '0047_alter_clientdecision_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcredit',
            name='acted',
            field=models.CharField(choices=[('yes', 'Ха'), ('no', 'Не')], max_length=50, verbose_name='acted'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='division.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='credit_purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request_credit.creditpurpose', verbose_name='credit purpose'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='currency_new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_new', to='division.currency', verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='current_debt',
            field=models.CharField(choices=[('yes', 'Ха'), ('no', 'Не')], max_length=50, verbose_name='current debt'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='economic_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request_credit.economicactivity', verbose_name='economic activity'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='economic_activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request_credit.economicactivitytype', verbose_name='economic activity type'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='family_number',
            field=models.IntegerField(verbose_name='family number'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='family_number_has_income',
            field=models.IntegerField(verbose_name='family number has income'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='full_time_employees',
            field=models.IntegerField(verbose_name='number of full-time employees?'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='information_source',
            field=models.CharField(choices=[('tv', 'Реклама дар телевизион'), ('radio', 'Реклама дар радио'), ('newspaper', 'Реклама дар рӯзнома'), ('internet', 'Реклама дар интернет'), ('banner', 'Баннер/шитҳо'), ('oxus', 'Корманди Оксус'), ('third_person', 'Шахси сеюм'), ('other', 'Дигар')], max_length=50, verbose_name='source of information'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='investment_sector',
            field=models.CharField(choices=[('trad', 'Савдо'), ('service', 'Хизматрасонӣ'), ('production', 'Истеҳсолот'), ('horticulture', 'Растанипарварӣ'), ('livestock', 'Чорвопарварӣ'), ('cons', 'Истеъмолӣ')], max_length=50, verbose_name='investment sector'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='new_job',
            field=models.IntegerField(verbose_name='creation of new jobs'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='request_amount',
            field=models.IntegerField(verbose_name='request amount'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='request_grace_period',
            field=models.IntegerField(verbose_name='request grace period'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='request_installment',
            field=models.IntegerField(verbose_name='request installment'),
        ),
        migrations.AlterField(
            model_name='requestcredit',
            name='work_experience',
            field=models.IntegerField(verbose_name='work experience'),
        ),
    ]
