# Generated by Django 4.1.2 on 2024-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone3',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='phone 3'),
        ),
    ]
