from dynamic_rest.serializers import DynamicModelSerializer
from dynamic_rest.serializers import DynamicRelationField
from .model import ReportHistory



class ReportHistorySerializer(DynamicModelSerializer):

    report = DynamicRelationField(
        "reports.models.report.serializer.ReportSerializer",
        label = 'report',
    )

    generated_by = DynamicRelationField(
        "users.serializer.UserSerializer",
        label="generated by",
        read_only=True,
    )

    class Meta:
        name = 'reporthistory'
        model = ReportHistory
        fields = (
            'id',
            'report',
            'created',
            'generated_by',
            'updated',
            'info',
            'duration',
            'xlsx_report',
        )
