from dynamic_rest.serializers import DynamicModelSerializer
from dynamic_rest.serializers import DynamicRelationField

from .model import CRIF


class CRIFSerializer(DynamicModelSerializer):
    generated_by = DynamicRelationField(
        "users.serializer.UserSerializer",
        label="generated by",
        read_only=True,
    )
    request_credit = DynamicRelationField(
        "request_credit.models.r_credit.serializer.RequestCreditSerializer",
        label="request_credit",
    )
    type = DynamicRelationField(
        "scoring.models.scoring_type.serializer.ScoringTypeSerializer",
        label="type",
    )
    parent = DynamicRelationField(
        "scoring.models.crif.serializer.CRIFSerializer",
        label="parent",
    )

    class Meta:
        name = "crif"

        model = CRIF
        fields = (
            'id',
            'created',
            'generated_by',
            'request_credit',
            'abacus_customer_id',
            'abacus_credit_id',
            'abacus_account_number',
            'data',
            'crif_credit_id',
            'type',
            'parent',
        )
