# Generated by Django 4.1.2 on 2024-02-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'permissions': [('can-change-terminal-payments_terminal', 'Can change terminal payments')], 'verbose_name': 'terminal', 'verbose_name_plural': 'terminals'},
        ),
    ]
