# Generated by Django 4.1.2 on 2024-02-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    def add_reports(apps, schema_editor):
        Report = apps.get_model('reports', 'Report')
        # Report.objects.create(report_name="swift-loan requests", uid="SWIFT LOAN")
     
    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_reports)
    ]
