# Generated by Django 4.1.2 on 2024-02-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reporthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(default='', max_length=255, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='info',
            field=models.CharField(default='', max_length=255, verbose_name='info'),
        ),
    ]
