# Generated by Django 4.1.2 on 2024-02-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    def add_reports(apps, schema_editor):
        Report = apps.get_model('reports', 'Report')
        Report.objects.create(report_name="Swift loan", uid="SWIFT-LOAN",category = "SwiftLoan")
        Report.objects.create(report_name="Swift loan break down", uid="SWIFT-LOAN-BREAK",category = "SwiftLoan")
    
    dependencies = [
        ('reports', '0004_report_category_reporthistory_info'),
    ]

    operations = [
        migrations.RunPython(add_reports)
    ]
