# Generated by Django 4.1.2 on 2024-02-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    def add_reports(apps, schema_editor):
        Report = apps.get_model('reports', 'Report')
        Report.objects.create(report_name="Active loans", uid="ABACUS-ACTIVE-LOAN",category = "Abacus")
        Report.objects.create(report_name="OLB per loan", uid="ABACUS-OLB-PER-LOAN",category = "Abacus")

    dependencies = [
        ('reports', '0005_auto_20240228_1012'),
    ]

    operations = [
        migrations.RunPython(add_reports)
    ]
