# Generated by Django 4.1.2 on 2024-03-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20240229_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporthistory',
            options={'verbose_name': 'report History', 'verbose_name_plural': 'report histories'},
        ),
    ]
