# Generated by Django 4.1.2 on 2024-03-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='permission_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='permission name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_name',
            field=models.CharField(default='', max_length=255, verbose_name='report name'),
        ),
    ]
