# Generated by Django 4.1.2 on 2024-03-11 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_report_permission_name_alter_report_report_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('report-abacus-olb-per-loan_report', 'Report: Abacus OLB per loans'), ('report-abacus-active-loan_report', 'Report: Abacus Active loans'), ('report-swift-loan_report', 'Report: Swift loans'), ('report-swift-loan-break_report', 'Report: Swift loans break down')), 'verbose_name': 'Reports', 'verbose_name_plural': 'Reports'},
        ),
    ]
