# Generated by Django 4.1.2 on 2024-03-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='permission_name',
        ),
    ]
