# Generated by Django 4.1.2 on 2024-03-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_reporthistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporthistory',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='duration'),
        ),
        migrations.AddField(
            model_name='reporthistory',
            name='xlsx_report',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='report'),
        ),
        migrations.AlterField(
            model_name='reporthistory',
            name='info',
            field=models.JSONField(blank=True, null=True, verbose_name='info'),
        ),
    ]
