# Generated by Django 4.1.2 on 2024-04-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_remove_reporthistory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('report-abacus-olb-per-loan_report', 'Report: Abacus OLB per loans'), ('report-abacus-active-loan_report', 'Report: Abacus Active loans'), ('report-swift-loan_report', 'Report: Swift loans'), ('report-swift-loan-break_report', 'Report: Swift loans break down'), ('report-abacus-swift-loan_report', 'Report: Abacus client list for Swift loan')), 'verbose_name': 'Reports', 'verbose_name_plural': 'Reports'},
        ),
    ]
