# Generated by Django 4.1.2 on 2024-03-14 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0002_customerscantype_customerscan_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerscantype',
            options={'verbose_name': 'customer scans types', 'verbose_name_plural': 'customer scans types'},
        ),
        migrations.AlterField(
            model_name='customerscan',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.customerscantype'),
        ),
    ]