# Generated by Django 4.1.2 on 2024-03-19 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import scan.models.credit_scan.model


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan', '0004_customerscan_abacus_id_alter_customerscan_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('uid', models.CharField(blank=True, help_text='Unique identifier for reference to record from code. Do not change if set!', max_length=30, null=True, unique=True)),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'credits scans types',
                'verbose_name_plural': 'credits scans types',
            },
        ),
        migrations.CreateModel(
            name='CreditScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('file', models.FileField(upload_to=scan.models.credit_scan.model.get_credit_scan_path, verbose_name='file')),
                ('abacus_id', models.IntegerField(blank=True, null=True, verbose_name='abacus_ID')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan.creditscantype')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'credits scans',
                'verbose_name_plural': 'credits scans',
            },
        ),
    ]
