# Generated by Django 4.1.2 on 2024-04-02 09:08

from django.db import migrations, models
import scan.models.credit_scan.model
import scan.models.customer_scan.model
import scan.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0005_creditscantype_creditscan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditscan',
            options={'verbose_name': 'Credit Scan', 'verbose_name_plural': 'Credit Scans'},
        ),
        migrations.AddField(
            model_name='creditscan',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='customerscan',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='creditscan',
            name='abacus_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Abacus ID'),
        ),
        migrations.AlterField(
            model_name='creditscan',
            name='file',
            field=models.FileField(upload_to=scan.models.credit_scan.model.get_credit_scan_path, validators=[scan.utils.utils.only_pdf], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='customerscan',
            name='file',
            field=models.FileField(upload_to=scan.models.customer_scan.model.get_customer_scan_path, validators=[scan.utils.utils.only_pdf], verbose_name='file'),
        ),
    ]
