# Generated by Django 4.1.2 on 2024-04-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0006_alter_creditscan_options_creditscan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditscan',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='customerscan',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='description'),
        ),
    ]
