# Generated by Django 4.1.2 on 2024-04-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request_credit', '0030_delete_cibthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='updated')),
                ('abacus_customer_id', models.IntegerField(blank=True, null=True, verbose_name='Абакус клиент Id')),
                ('abacus_credit_id', models.IntegerField(blank=True, null=True, verbose_name='Абакус кредит Id')),
                ('credit_id', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Абакус контракт коде')),
                ('data', models.JSONField(verbose_name='data')),
                ('has_not_history', models.BooleanField(default=False, verbose_name='has not history')),
                ('crif_credit_id', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='код контракта в КИБТ')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('request_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request_credit.requestcredit', verbose_name='Swift id')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'CRIF',
                'verbose_name_plural': 'CRIFs',
            },
        ),
    ]
