# Generated by Django 4.1.2 on 2024-04-19 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_rename_credit_id_crif_abacus_account_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crif',
            options={'permissions': (('can-crif-get-information-abacus_crif', 'Custom: Can crif get information (abacus)'), ('can-crif-get-information-swift_crif', 'Custom: Can crif get information (swift)'), ('can-crif-generate-client-report_crif', 'Custom: Can crif generate client report')), 'verbose_name': 'CRIF', 'verbose_name_plural': 'CRIFs'},
        ),
    ]
