# Generated by Django 4.1.2 on 2024-05-07 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0005_alter_crif_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crif',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='crif',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='crif',
            name='generated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='generated by'),
        ),
    ]
