# Generated by Django 4.1.2 on 2024-08-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_chartaccount_ru_name_chartaccount_tj_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartaccount',
            options={'verbose_name': 'chart account', 'verbose_name_plural': 'Chart Accounts'},
        ),
        migrations.AlterModelOptions(
            name='generalledger',
            options={'verbose_name': 'general ledger', 'verbose_name_plural': 'General Ledgers'},
        ),
        migrations.AlterField(
            model_name='chartaccount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='chartaccount',
            name='ru_name',
            field=models.CharField(max_length=100, verbose_name='Ru name'),
        ),
        migrations.AlterField(
            model_name='chartaccount',
            name='tj_name',
            field=models.CharField(max_length=100, verbose_name='TJ name'),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
