# Generated by Django 4.1.2 on 2024-08-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_chartaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='general_ledgers', to='accounting.chartaccount', verbose_name='Account'),
        ),
    ]
