# Generated by Django 4.1.2 on 2024-08-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_generalledger_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=500, verbose_name='Код')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
            ],
        ),
    ]
