# Generated by Django 4.1.2 on 2024-08-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.TextField(max_length=100, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(max_length=350, verbose_name='Описание'),
        ),
    ]
