# Generated by Django 4.1.2 on 2024-08-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_account_code_alter_account_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
