# Generated by Django 4.1.2 on 2024-08-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartaccount',
            name='account_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Account Number'),
        ),
    ]
